Traceback (most recent call last):
  File "/usr/share/miniconda/envs/buildjupyterbook/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/share/miniconda/envs/buildjupyterbook/lib/python3.10/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda/envs/buildjupyterbook/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/share/miniconda/envs/buildjupyterbook/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/share/miniconda/envs/buildjupyterbook/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda/envs/buildjupyterbook/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda/envs/buildjupyterbook/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Download the file that we need to run these examples
os.makedirs('../data', exist_ok=True)
filepath_lp= '../data/pfa20240108.001_lp_fit_01min.001.h5 '
filepath_ac= '../data/pfa20240108.001_ac_fit_01min.001.h5 '

if not os.path.exists(filepath_lp):

    fileList = data.getExperimentFiles(expList[0].id)
    for file0 in fileList:
        if file0.kindatdesc == 'Fitted - Long Pulse (F-region) - 1 min':
            file2download = file0.name
            break
        
    print('Downloading data file...')

    file = data.downloadFile(file2download, filepath_lp, 
                               user_fullname, user_email, user_affiliation,'hdf5')    
    print('...Done!')

else:
    print(f"File {filepath_lp} already downloaded")


if not os.path.exists(filepath_ac):

    fileList = data.getExperimentFiles(expList[0].id)
    for file0 in fileList:
        if file0.kindatdesc == 'Fitted - Alternating Code (E-region) - 1 min':
            file2download = file0.name
            break
        
    print('Downloading data file...')

    file = data.downloadFile(file2download, filepath_ac, 
                               user_fullname, user_email, user_affiliation,'hdf5')    
    print('...Done!')

else:
    print(f"File {filepath_ac} already downloaded")
------------------

----- stdout -----
Downloading data file...
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[4], line 16[0m
[1;32m     12[0m             [38;5;28;01mbreak[39;00m
[1;32m     14[0m     [38;5;28mprint[39m([38;5;124m'[39m[38;5;124mDownloading data file...[39m[38;5;124m'[39m)
[0;32m---> 16[0m     file [38;5;241m=[39m data[38;5;241m.[39mdownloadFile([43mfile2download[49m, filepath_lp, 
[1;32m     17[0m                                user_fullname, user_email, user_affiliation,[38;5;124m'[39m[38;5;124mhdf5[39m[38;5;124m'[39m)    
[1;32m     18[0m     [38;5;28mprint[39m([38;5;124m'[39m[38;5;124m...Done![39m[38;5;124m'[39m)
[1;32m     20[0m [38;5;28;01melse[39;00m:

[0;31mNameError[0m: name 'file2download' is not defined

